// table schema generated by introspection
import {
  mysqlTable,
  mysqlSchema,
  AnyMySqlColumn,
  primaryKey,
  unique,
  serial,
  varchar,
  int,
} from "drizzle-orm/mysql-core";
import { sql } from "drizzle-orm";

export const usersTable = mysqlTable(
  "users_table",
  {
    id: int("id").primaryKey().autoincrement(),
    name: varchar("name", { length: 255 }).notNull(),
    age: int("age").notNull(),
    email: varchar("email", { length: 255 }).notNull(),
  },
  (table) => {
    return {
      usersTableId: primaryKey({ columns: [table.id], name: "users_table_id" }),
      id: unique("id").on(table.id),
      usersTableEmailUnique: unique("users_table_email_unique").on(table.email),
    };
  }
);
